feat(typescript): add rcbc
C-Accel-CRIPT/criptscripts pull request #12
Opened 2023-04-21 19:31 UTC by bearmit

2023-04-21 19:38 UTC, bearmit commented on scripts/typescript/package.json
> +    "bcdb": "npx ts-node ./src/bcdb",
I was working on two datasets at the time, that's why you can see some traces of it. Another PR is coming.

2023-04-21 22:40 UTC, nh916 commented
I don't know enough to provide an effective review, but I ran this PR locally and it seems to work fine. 

The only note I have is regarding `Link to TypeScript source code` and I think that could be improved and changed to instead say `TypeScript source code on GitHub`. I think that could also earn us some SEO points as well. 
I wrote a small [SEO links wiki](https://github.com/C-Accel-CRIPT/criptscripts/wiki/How-to-use-links-effectively) within the [CRIPT Scripts repository](https://github.com/C-Accel-CRIPT/criptscripts) that I thought could be helpful for us

2023-04-21 22:41 UTC, nh916 approved these changes

2023-04-21 23:36 UTC, bearmit commented
@nh916 Thanks. I would like to wait a little bit in case @shijiale0609 have a moment to look at the graph sources (in src/rcbc/data/graph) next week.

2023-04-22 01:26 UTC, shijiale0609 requested changes
computations.ts, PPV-b-PI-89. There is no computation in the graph which was polished by Brad. see the last slide https://docs.google.com/presentation/d/1eXM7870YM2sxQQvMFahI2Ox8-EFCGaw_/edit#slide=id.p3

2023-04-25 13:12 UTC, merged

2023-04-25 16:33 UTC, nh916 commented
@bearmit be sure to delete branches that you are not using, its just good to keep the repository clean